const hotStocks_example = [
  {
    type: 20,
    code: 'SH601127',
    name: '赛力斯',
    value: 31232,
    increment: 356,
    rank_change: 0,
    has_exist: null,
    symbol: 'SH601127',
    percent: 10.01,
    current: 55.72,
    chg: 5.07,
    exchange: 'SH',
    stock_type: 11,
    sub_type: 'ASH',
    ad: 0,
    trade_session: null,
    current_ext: null,
    percent_ext: null,
  },
  {
    type: 20,
    code: 'SH603361',
    name: '浙江国祥',
    value: 25301,
    increment: -203,
    rank_change: 0,
    has_exist: null,
    symbol: 'SH603361',
    percent: null,
    current: null,
    chg: null,
    exchange: 'SH',
    stock_type: 11,
    sub_type: null,
    ad: 0,
    trade_session: null,
    current_ext: null,
    percent_ext: null,
  },
  {
    type: 20,
    code: 'SZ002456',
    name: '欧菲光',
    value: 17379,
    increment: 139,
    rank_change: 0,
    has_exist: null,
    symbol: 'SZ002456',
    percent: 9.97,
    current: 6.4,
    chg: 0.58,
    exchange: 'SZ',
    stock_type: 11,
    sub_type: '1',
    ad: 0,
    trade_session: null,
    current_ext: null,
    percent_ext: null,
  },
  {
    type: 20,
    code: 'SH601888',
    name: '中国中免',
    value: 12772,
    increment: 171,
    rank_change: 0,
    has_exist: null,
    symbol: 'SH601888',
    percent: -1.42,
    current: 105.97,
    chg: -1.53,
    exchange: 'SH',
    stock_type: 11,
    sub_type: 'ASH',
    ad: 0,
    trade_session: null,
    current_ext: null,
    percent_ext: null,
  },
  {
    type: 20,
    code: 'SH603496',
    name: '恒为科技',
    value: 11361,
    increment: 167,
    rank_change: 0,
    has_exist: null,
    symbol: 'SH603496',
    percent: 9.99,
    current: 29.74,
    chg: 2.7,
    exchange: 'SH',
    stock_type: 11,
    sub_type: 'ASH',
    ad: 0,
    trade_session: null,
    current_ext: null,
    percent_ext: null,
  },
  {
    type: 20,
    code: 'SZ002281',
    name: '光迅科技',
    value: 8886,
    increment: 102,
    rank_change: 0,
    has_exist: null,
    symbol: 'SZ002281',
    percent: 0.72,
    current: 32.26,
    chg: 0.23,
    exchange: 'SZ',
    stock_type: 11,
    sub_type: '1',
    ad: 0,
    trade_session: null,
    current_ext: null,
    percent_ext: null,
  },
  {
    type: 20,
    code: 'SZ300351',
    name: '永贵电器',
    value: 8740,
    increment: 0,
    rank_change: 0,
    has_exist: null,
    symbol: 'SZ300351',
    percent: 0.82,
    current: 13.46,
    chg: 0.11,
    exchange: 'SZ',
    stock_type: 11,
    sub_type: '3',
    ad: 0,
    trade_session: null,
    current_ext: null,
    percent_ext: null,
  },
  {
    type: 20,
    code: 'PDD',
    name: '拼多多',
    value: 8078,
    increment: -128,
    rank_change: 0,
    has_exist: null,
    symbol: 'PDD',
    percent: 7.4014,
    current: 105.64,
    chg: 7.28,
    exchange: 'NASDAQ',
    stock_type: 0,
    sub_type: '1536',
    ad: 0,
    trade_session: 3,
    current_ext: 106.01,
    percent_ext: 0.350246,
  },
]
